import { RoleName } from "@prisma/client";
import { PERMISSIONS } from "./permissions";

export const ROLE_PERMISSIONS: Record<RoleName, string[]> = {
  SUPER_ADMIN: Object.values(PERMISSIONS),
  ADMIN: [
    PERMISSIONS.DASHBOARD_VIEW, PERMISSIONS.USERS_READ, PERMISSIONS.USERS_CREATE, PERMISSIONS.USERS_UPDATE, PERMISSIONS.USERS_MANAGE_ROLES,
    PERMISSIONS.ROLES_READ, PERMISSIONS.WORKERS_READ, PERMISSIONS.WORKERS_CREATE, PERMISSIONS.WORKERS_UPDATE,
    PERMISSIONS.EMPLOYERS_READ, PERMISSIONS.EMPLOYERS_CREATE, PERMISSIONS.EMPLOYERS_UPDATE, PERMISSIONS.JOBS_READ, PERMISSIONS.JOBS_CREATE,
    PERMISSIONS.JOBS_UPDATE, PERMISSIONS.APPLICATIONS_READ, PERMISSIONS.APPLICATIONS_UPDATE, PERMISSIONS.VERIFICATION_READ,
    PERMISSIONS.VERIFICATION_UPDATE, PERMISSIONS.ATTENDANCE_READ, PERMISSIONS.ATTENDANCE_UPDATE, PERMISSIONS.PAYMENTS_READ,
    PERMISSIONS.REPORTS_READ, PERMISSIONS.NOTIFICATIONS_READ,
  ],
  VERIFICATION_AGENT: [PERMISSIONS.DASHBOARD_VIEW, PERMISSIONS.WORKERS_READ, PERMISSIONS.VERIFICATION_READ, PERMISSIONS.VERIFICATION_UPDATE, PERMISSIONS.DOCUMENTS_READ],
  EMPLOYER: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.WORKERS_READ,
    PERMISSIONS.JOBS_READ, PERMISSIONS.JOBS_CREATE, PERMISSIONS.JOBS_UPDATE,
    PERMISSIONS.APPLICATIONS_READ, PERMISSIONS.APPLICATIONS_UPDATE,
    PERMISSIONS.ATTENDANCE_READ, PERMISSIONS.PAYMENTS_READ,
  ],
  SUPERVISOR: [PERMISSIONS.DASHBOARD_VIEW, PERMISSIONS.WORKERS_READ, PERMISSIONS.ATTENDANCE_READ, PERMISSIONS.ATTENDANCE_UPDATE, PERMISSIONS.JOBS_READ, PERMISSIONS.APPLICATIONS_READ],
  WORKER: [PERMISSIONS.DASHBOARD_VIEW, PERMISSIONS.JOBS_READ, PERMISSIONS.ATTENDANCE_READ, PERMISSIONS.PAYMENTS_READ],
};