"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { ArrowLeft, ArrowRight, BriefcaseBusiness, CheckCircle2, Clock3, Phone, RefreshCw, Sparkles, Target, TrendingUp, Users, UserRound } from "lucide-react";
import { EmployerShell } from "@/components/layout/employer-shell";

type Candidate = { workerId?: string; workerCode?: string; firstName?: string; lastName?: string; phone?: string | null; matchScore?: number; conversionScore?: number; reasons?: string[]; outreach?: { status?: string } | null };
type Dashboard = { success: boolean; mode: string; job: { id: string; title: string; status?: string }; summary: Record<string, number>; funnel: Array<{ stage: string; count: number }>; contactNow: Candidate[]; followUpsDue: Candidate[]; highConversionCandidates: Candidate[]; candidatesLosingInterest: Candidate[] };

const api = (id: string) => `/api/backend/jobs/${id}/recruitment-ai/dashboard`;
const nameOf = (c: Candidate) => [c.firstName, c.lastName].filter(Boolean).join(" ") || c.workerCode || "Worker";
const statusClass = (s?: string) => s === "INTERESTED" || s === "INTERVIEW" || s === "SELECTED" || s === "HIRED" ? "bg-emerald-50 text-emerald-700" : s === "NO_RESPONSE" || s === "UNAVAILABLE" ? "bg-amber-50 text-amber-700" : s === "NOT_INTERESTED" || s === "WRONG_NUMBER" ? "bg-red-50 text-red-700" : "bg-blue-50 text-blue-700";

function CandidateRow({ candidate, jobId }: { candidate: Candidate; jobId: string }) {
  const workspace = candidate.workerId ? `/employer/jobs/${jobId}/recruitment/${candidate.workerId}` : `/employer/jobs/${jobId}`;
  return <div className="flex flex-col gap-4 border-b border-slate-100 px-5 py-4 last:border-b-0 lg:flex-row lg:items-center lg:justify-between">
    <div className="flex min-w-0 items-start gap-3"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-blue-50 text-blue-700"><UserRound size={17} /></div><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><span className="font-bold text-slate-900">{nameOf(candidate)}</span>{candidate.workerCode && <span className="text-[10px] font-semibold uppercase tracking-wide text-slate-400">{candidate.workerCode}</span>}</div><div className="mt-1 flex flex-wrap items-center gap-2 text-xs text-slate-500"><span className="font-semibold text-blue-700">{candidate.matchScore ?? 0}% match</span><span>•</span><span>{candidate.conversionScore ?? 0}% conversion</span>{candidate.outreach?.status && <><span>•</span><span className={`rounded-full px-2 py-0.5 font-bold ${statusClass(candidate.outreach.status)}`}>{candidate.outreach.status.replaceAll("_", " ")}</span></>}</div>{candidate.reasons?.length ? <p className="mt-2 line-clamp-2 text-xs text-slate-500">{candidate.reasons.slice(0, 2).join(" · ")}</p> : null}</div></div>
    <div className="flex shrink-0 items-center gap-2">{candidate.phone && <a href={`tel:${candidate.phone}`} className="inline-flex items-center gap-1.5 rounded-lg border border-slate-200 px-3 py-2 text-xs font-semibold text-slate-700 hover:bg-slate-50"><Phone size={14} /> Call</a>}<Link href={workspace} className="inline-flex items-center gap-1.5 rounded-lg bg-[#0757d8] px-3 py-2 text-xs font-semibold text-white hover:bg-[#064dbf]">Review<ArrowRight size={13} /></Link></div>
  </div>;
}

function Queue({ title, icon: Icon, candidates, empty, jobId }: { title: string; icon: typeof Target; candidates: Candidate[]; empty: string; jobId: string }) {
  return <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b border-slate-100 px-5 py-4"><div className="flex items-center gap-2.5"><div className="flex h-8 w-8 items-center justify-center rounded-lg bg-blue-50 text-blue-700"><Icon size={16} /></div><h2 className="text-sm font-bold text-slate-900">{title}</h2></div><span className="rounded-full bg-slate-100 px-2.5 py-1 text-[11px] font-bold text-slate-600">{candidates.length}</span></div>{candidates.length ? candidates.map((c, i) => <CandidateRow key={`${c.workerId ?? c.workerCode ?? "candidate"}-${i}`} candidate={c} jobId={jobId} />) : <div className="px-5 py-10 text-center text-xs text-slate-500">{empty}</div>}</section>;
}

export default function AiRecruiterDashboardPage({ params }: { params: Promise<{ id: string }> }) {
  const [dashboard, setDashboard] = useState<Dashboard | null>(null); const [jobId, setJobId] = useState<string | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  async function load(id: string) { setLoading(true); setError(null); try { const response = await fetch(api(id), { credentials: "include", cache: "no-store" }); const data = await response.json().catch(() => null); if (!response.ok) throw new Error(data?.message || "Unable to load AI recruiter dashboard"); setDashboard(data); } catch (err) { setError(err instanceof Error ? err.message : "Unable to load AI recruiter dashboard"); } finally { setLoading(false); } }
  useEffect(() => { void (async () => { const { id } = await params; setJobId(id); await load(id); })(); }, [params]);
  const summary = dashboard?.summary ?? {}; const stages = dashboard?.funnel ?? []; const maxFunnel = Math.max(...stages.map((s) => s.count), 1);
  return <EmployerShell><div className="mb-6 flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-start gap-3"><Link href={jobId ? `/employer/jobs/${jobId}` : "/employer/jobs"} className="mt-1 rounded-lg border border-slate-200 bg-white p-2 text-slate-600 hover:bg-slate-50"><ArrowLeft size={17} /></Link><div><div className="flex items-center gap-2"><Sparkles size={18} className="text-blue-600" /><h1 className="text-2xl font-extrabold tracking-tight text-slate-900">AI Recruiter</h1></div><p className="mt-1 text-xs text-slate-500">AI-ranked recruitment actions for your shortlisted workforce.</p></div></div><button type="button" disabled={!jobId || loading} onClick={() => jobId && void load(jobId)} className="inline-flex items-center justify-center gap-2 rounded-lg border border-slate-200 bg-white px-3.5 py-2.5 text-xs font-semibold text-slate-700 hover:bg-slate-50 disabled:opacity-50"><RefreshCw size={14} className={loading ? "animate-spin" : ""} /> Refresh AI insights</button></div>
  {loading && <div className="rounded-2xl border border-slate-200 bg-white p-12 text-center text-sm text-slate-500">Loading AI recruitment insights...</div>}{error && <div className="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}
  {!loading && !error && dashboard && <><section className="mb-6 rounded-2xl bg-gradient-to-r from-[#0757d8] to-[#0b74e8] p-6 text-white shadow-sm"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><div className="text-xs font-semibold uppercase tracking-[.16em] text-blue-100">AI Recruitment Command Center</div><h2 className="mt-1 text-xl font-extrabold">{dashboard.job.title}</h2><p className="mt-1 text-sm text-blue-100">Prioritize the workers most likely to convert and keep every follow-up on track.</p></div><div className="flex items-center gap-2 rounded-xl bg-white/10 px-4 py-3"><BriefcaseBusiness size={18} /><span className="text-xs font-bold">{dashboard.job.status ?? "ACTIVE"}</span></div></div></section>
  <section className="mb-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-6">{[["Matched", summary.totalMatchedWorkers ?? 0, Users], ["Not contacted", summary.notContacted ?? 0, UserRound], ["Contacted", summary.contacted ?? 0, Phone], ["Interested", summary.interested ?? 0, TrendingUp], ["Follow-ups due", summary.followUpsDue ?? 0, Clock3], ["High conversion", summary.highConversionCandidates ?? 0, Target]].map(([label, value, Icon]) => <div key={String(label)} className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex items-center justify-between"><span className="text-xs font-semibold text-slate-500">{String(label)}</span><Icon size={16} className="text-blue-600" /></div><div className="mt-2 text-2xl font-extrabold text-slate-900">{String(value)}</div></div>)}</section>
  <section className="mb-6 grid gap-5 lg:grid-cols-[1.4fr_.6fr]"><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="mb-5 flex items-center justify-between"><div><h2 className="text-sm font-bold text-slate-900">Recruitment funnel</h2><p className="mt-1 text-xs text-slate-500">Progress from AI match to hire.</p></div><CheckCircle2 size={18} className="text-emerald-600" /></div><div className="space-y-3">{stages.map((stage) => <div key={stage.stage} className="grid grid-cols-[92px_1fr_40px] items-center gap-3 text-xs"><span className="font-semibold text-slate-600">{stage.stage.replaceAll("_", " ")}</span><div className="h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-[#0757d8]" style={{ width: `${Math.max((stage.count / maxFunnel) * 100, stage.count ? 6 : 0)}%` }} /></div><span className="text-right font-bold text-slate-900">{stage.count}</span></div>)}</div></div><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-sm font-bold text-slate-900">Pipeline health</h2><p className="mt-1 text-xs text-slate-500">Current outreach distribution.</p><div className="mt-5 space-y-3">{[["No response", summary.noResponse ?? 0], ["Interview", summary.interview ?? 0], ["Selected", summary.selected ?? 0], ["Hired", summary.hired ?? 0]].map(([label, value]) => <div key={String(label)} className="flex items-center justify-between rounded-lg bg-slate-50 px-3 py-2.5"><span className="text-xs font-semibold text-slate-600">{String(label)}</span><span className="text-sm font-extrabold text-slate-900">{String(value)}</span></div>)}</div></div></section>
  <section className="grid gap-5 lg:grid-cols-2"><Queue title="Contact now" icon={Target} candidates={dashboard.contactNow} empty="No immediate contact actions. Your pipeline is up to date." jobId={dashboard.job.id} /><Queue title="Follow-ups due" icon={Clock3} candidates={dashboard.followUpsDue} empty="No overdue follow-ups right now." jobId={dashboard.job.id} /><Queue title="High conversion candidates" icon={TrendingUp} candidates={dashboard.highConversionCandidates} empty="No high-conversion candidates yet." jobId={dashboard.job.id} /><Queue title="Candidates losing interest" icon={Users} candidates={dashboard.candidatesLosingInterest} empty="No candidates currently flagged as losing interest." jobId={dashboard.job.id} /></section></>}
  </EmployerShell>;
}
